### ISSUE TITLE
balancer: wrong calculation of required signatures

### ISSUE THREAD

**Issue by francolq** [joinplank/cardano-devtools#31]
https://github.com/joinplank/cardano-devtools/blob/e440e554a5f213d4c335f28e2c9f6fc0fd89c2ae/balancer.ts#LL329C30-L329C30

Function calculateNeededVkeyWitnesses is not considering the required signers field.

Also, it is building a set of addresses (addressSetOfUsedWalletUtxos) and this is wrong (because addresses does not only include public keys but also staking keys).

The solution is to extract the public keys from the addresses and build a set of public keys, also adding the public keys from the required signers field (field 14 of the tx body).

To extract the public keys from the addresses this code can be copied:
https://github.com/joinplank/cardano-devtools/blob/e440e554a5f213d4c335f28e2c9f6fc0fd89c2ae/walletWrapper.ts#L72

**Comment by a-osiecki** [comment]
solved in [dfb0c79](https://github.com/joinplank/cardano-devtools/commit/dfb0c792bdc58a9fb49d770318043cb0add38c14)
